
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Using the environment variables
const SUPABASE_URL = "https://tlqilvhbjxrtocvsidpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscWlsdmhianhydG9jdnNpZHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTk1NDYsImV4cCI6MjA1OTk5NTU0Nn0.40ayOho2PMVln_5lO0TzYuWLP3G_cD9-ilCLTHZHdlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
